# Generated by Django 4.1.13 on 2024-08-26 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='jobs_submitted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='max_jobs_allowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='subscription_plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='final_csv_file',
            field=models.FileField(blank=True, null=True, upload_to='postprocessed_files/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='initial_csv_file',
            field=models.FileField(blank=True, null=True, upload_to='initial_files/'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OneTimePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
